services:
  nginx:
    image: cheftory/cheftory-nginx-gateway-dev:latest
    container_name: cheftory-gateway-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    restart: always
    networks:
      - cheftory_network

  proxy-server:
    image: cheftory/cheftory-proxy-server-dev:latest
    container_name: proxy-server
    expose:
      - "8080"
    restart: always
    networks:
      - cheftory_network

  ai-voice-command:
    image: cheftory/cheftory-ai-voice-command-server-dev:latest
    container_name: ai-voice-command
    expose:
      - "8000"
    restart: always
    networks:
      - cheftory_network

networks:
  cheftory_network:
    name: dev_cheftory_network
    driver: bridge
