version: '3.9'

services:
  proxy-server:
    image: cheftory/cheftory-proxy-server-dev:latest
    container_name: proxy-server
    ports:
      - "8080:8080"
    networks:
      - cheftory_network

  nginx:
    image: cheftory/cheftory-nginx-gateway-dev:latest
    container_name: cheftory-gateway-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    restart: always
    networks:
      - cheftory_network
    depends_on:
      - proxy-server

networks:
  cheftory_network:
    name: dev_cheftory_network
    driver: bridge