version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/cheftories.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/cheftories.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - /var/www/html:/var/www/html:rw
      - /var/www/certbot:/var/www/certbot:ro
    restart: always
    networks:
      - cheftory_network

networks:
  cheftory_network:
    name: dev_cheftory_network
    driver: bridge