version: '3.9'

services:
  nginx:
    image: cheftory-nginx-gateway-dev:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - cheftory_network

networks:
  cheftory_network:
    name: dev_cheftory_network
    driver: bridge